from pathlib import Path

configfile: "config/config.yaml"
configfile: "config/targets.yaml"


OUTDIR = Path(config["OUTPUT_DIRECTORY"])
LOGDIR = OUTDIR / "logs"
REPORT_DIR_PLOTS = Path(OUTDIR / "report/plots")
REPORT_DIR_TABLES = Path(OUTDIR / "report/tables")

rule all:
    input:
        expand(REPORT_DIR_PLOTS / "dim_plot.{reduction}.{legend}.png" reduction=config["DIM_PLOT"]["REDUCTIONS"], legend=config["DIM_PLOT"]["LEGENDS"]),
        REPORT_DIR_PLOTS / "heatmap.png",
        REPORT_DIR_PLOTS / "feature_plot.png",

include: "rules/preproces.smk",
include: "rules/plot.smk",